module.exports = {
  projects: [
    '<rootDir>/apps/dges-front',
    '<rootDir>/libs/ui/project-card',
    '<rootDir>/libs/ui/project-details',
    '<rootDir>/libs/store/projects/projects-firebase',
    '<rootDir>/libs/store/projects/projects-api',
    '<rootDir>/libs/types/project',
    '<rootDir>/libs/data/projects',
    '<rootDir>/libs/api/projects/firebase',
    '<rootDir>/libs/forms/project-form',
    '<rootDir>/libs/forms/login-form',
    '<rootDir>/libs/ui/login-dialog',
    '<rootDir>/libs/api/auth/firebase',
    '<rootDir>/libs/store/auth/firebase',
    '<rootDir>/libs/types/auth',
    '<rootDir>/libs/forms/chips',
    '<rootDir>/libs/ui/snackbar',
    '<rootDir>/libs/ui/confirm-dialog',
    '<rootDir>/libs/api/storage/firebase',
    '<rootDir>/libs/ui/drop-zone',
    '<rootDir>/libs/ui/upload-images',
    '<rootDir>/libs/ui/upload-task',
    '<rootDir>/libs/forms/upload-task',
    '<rootDir>/libs/forms/upload-images',
    '<rootDir>/libs/store/storage/firebase',
  ],
};
